#!/bin/bash

echo "Validating test.xml against test.xsd..."
emcc -O2 -s EMULATE_FUNCTION_POINTER_CASTS=1 ./build/xmllint.o \
	./build/.libs/libxml2.a ./libz.a -o ./xmllint.test.js \
	--embed-file ./test/test.xml --embed-file ./test/test.xsd
node ./xmllint.test.js --noout --schema ./test/test.xsd ./test/test.xml
rm -rf ./xmllint.test.js
rm -rf ./xmllint.test.js.mem

echo "Validating test.xml against test.rng..."
emcc -O2 -s EMULATE_FUNCTION_POINTER_CASTS=1 ./build/xmllint.o \
	./build/.libs/libxml2.a ./libz.a -o ./xmllint.test.js \
	--embed-file ./test/test.xml --embed-file ./test/test.rng
node ./xmllint.test.js --noout --relaxng ./test/test.rng ./test/test.xml
rm -rf ./xmllint.test.js
rm -rf ./xmllint.test.js.mem
